oauthClient:
  redirectUris:
  - https://potential-zebra-qwxg6946v29w5w-3000.app.github.dev/authorization-code/callback
  applicationType: web
trustedOrigins:
  - https://potential-zebra-qwxg6946v29w5w-3000.app.github.dev 

directions: |+2
  Okta configuration written to: .okta.env

  Sign into Okta and update your Okta application to enable Refresh Token
  
  Install the dependencies using npm:

      npm install

  Run this application with:

      npm start
